import type { Listing } from './listings'

export const mockListings: Listing[] = [
    {
        id: '405-myers-b30',
        mlsNumber: '405-MYERS-B30',
        address: {
            full: '405 MYERS Road Unit# B30, Cambridge, Ontario',
            streetNumber: '405',
            streetName: 'MYERS Road',
            unitNumber: 'B30',
            city: 'Cambridge',
            province: 'Ontario',
            postalCode: 'N1R 5A6',
        },
        price: 2220, // Monthly
        beds: 2,
        baths: 2,
        sqft: 920,
        lotSize: null,
        propertyType: 'Residential Leasing',
        yearBuilt: null,
        description: 'Modern 2-bedroom, 2-bathroom unit in a prime Cambridge location. Spacious layout with 920 sqft of living space. Perfect for those seeking a high-quality residential lease.',
        photos: ['/images/listing-placeholder.jpg'],
        listDate: new Date().toISOString(),
        daysOnMarket: 1,
        status: 'Active',
        virtualTour: null,
        features: { garage: 'Parking Included', heating: 'Forced Air', cooling: 'Central Air' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: 'https://www.realtor.ca/real-estate/27674251/405-myers-road-unit-b30-cambridge',
    },
    {
        id: 'mock-1',
        mlsNumber: 'X12345678',
        address: {
            full: '142 Williamsburg Road, Kitchener, ON N2E 1W8',
            streetNumber: '142',
            streetName: 'Williamsburg Road',
            unitNumber: null,
            city: 'Kitchener',
            province: 'ON',
            postalCode: 'N2E 1W8',
        },
        price: 849000,
        beds: 4,
        baths: 3,
        sqft: 2100,
        lotSize: '40 x 110 ft',
        propertyType: 'Detached',
        yearBuilt: 2005,
        description: 'Beautiful family home in sought-after Williamsburg neighbourhood. Open concept main floor, updated kitchen with granite countertops, hardwood throughout. Walking distance to top-rated schools.',
        photos: ['/images/house-1.jpg'],
        listDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        daysOnMarket: 3,
        status: 'Active',
        virtualTour: null,
        features: { garage: '2 Car Attached', heating: 'Forced Air Gas', cooling: 'Central Air' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        id: 'mock-2',
        mlsNumber: 'X12345679',
        address: {
            full: '88 Bridgeport Road E, Waterloo, ON N2J 2K4',
            streetNumber: '88',
            streetName: 'Bridgeport Road E',
            unitNumber: null,
            city: 'Waterloo',
            province: 'ON',
            postalCode: 'N2J 2K4',
        },
        price: 699000,
        beds: 3,
        baths: 2,
        sqft: 1650,
        lotSize: '35 x 100 ft',
        propertyType: 'Semi-Detached',
        yearBuilt: 1998,
        description: 'Tastefully updated semi in central Waterloo. New kitchen, renovated bathrooms, finished basement. Steps from the LRT and Uptown shops.',
        photos: ['/images/listing-placeholder.jpg'],
        listDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        daysOnMarket: 1,
        status: 'Active',
        virtualTour: null,
        features: { garage: '1 Car Detached', heating: 'Forced Air Gas', cooling: 'Central Air' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        id: 'mock-3',
        mlsNumber: 'X12345680',
        address: {
            full: '310 Lakeshore Road, Cambridge, ON N1R 5A6',
            streetNumber: '310',
            streetName: 'Lakeshore Road',
            unitNumber: null,
            city: 'Cambridge',
            province: 'ON',
            postalCode: 'N1R 5A6',
        },
        price: 589000,
        beds: 3,
        baths: 1,
        sqft: 1200,
        lotSize: '50 x 130 ft',
        propertyType: 'Detached',
        yearBuilt: 1975,
        description: 'Solid brick bungalow on a generous lot in a quiet Cambridge street. Great bones, updated windows and furnace. Perfect for first-time buyers or investors.',
        photos: ['/images/listing-placeholder.jpg'],
        listDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        daysOnMarket: 7,
        status: 'Active',
        virtualTour: null,
        features: { garage: 'None', heating: 'Forced Air Gas', cooling: 'None' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        id: 'mock-4',
        mlsNumber: 'X12345681',
        address: {
            full: '45 Doon Village Road, Kitchener, ON N2P 1A4',
            streetNumber: '45',
            streetName: 'Doon Village Road',
            unitNumber: null,
            city: 'Kitchener',
            province: 'ON',
            postalCode: 'N2P 1A4',
        },
        price: 1150000,
        beds: 4,
        baths: 4,
        sqft: 3200,
        lotSize: '55 x 120 ft',
        propertyType: 'Detached',
        yearBuilt: 2010,
        description: 'Luxury custom home in prestigious Doon South. Backs onto green space, walkout basement, chef kitchen, premium finishes throughout.',
        photos: ['/images/listing-placeholder.jpg'],
        listDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        daysOnMarket: 14,
        status: 'Active',
        virtualTour: null,
        features: { garage: '3 Car Attached', heating: 'Forced Air Gas', cooling: 'Central Air' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        id: 'mock-5',
        mlsNumber: 'X12345682',
        address: {
            full: '12 Caroline Street N, Waterloo, ON N2L 2Y2',
            streetNumber: '12',
            streetName: 'Caroline Street N',
            unitNumber: '504',
            city: 'Waterloo',
            province: 'ON',
            postalCode: 'N2L 2Y2',
        },
        price: 450000,
        beds: 1,
        baths: 1,
        sqft: 750,
        lotSize: null,
        propertyType: 'Condo',
        yearBuilt: 2018,
        description: 'Modern 1-bedroom condo in prime Uptown Waterloo location. Open concept, floor-to-ceiling windows, in-suite laundry, underground parking.',
        photos: ['/images/listing-placeholder.jpg'],
        listDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        daysOnMarket: 2,
        status: 'Active',
        virtualTour: null,
        features: { garage: '1 Underground', heating: 'Heat Pump', cooling: 'Central Air' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        id: 'mock-6',
        mlsNumber: 'X12345683',
        address: {
            full: '77 Forest Hill Drive, Kitchener, ON N2M 4G3',
            streetNumber: '77',
            streetName: 'Forest Hill Drive',
            unitNumber: null,
            city: 'Kitchener',
            province: 'ON',
            postalCode: 'N2M 4G3',
        },
        price: 725000,
        beds: 3,
        baths: 2,
        sqft: 1800,
        lotSize: '45 x 115 ft',
        propertyType: 'Detached',
        yearBuilt: 1982,
        description: 'Well-maintained split-level home in Forest Hill. Large private backyard, updated roof and windows. Perfect for growing families.',
        photos: ['/images/listing-placeholder.jpg'],
        listDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        daysOnMarket: 5,
        status: 'Active',
        virtualTour: null,
        features: { garage: '1 Car Attached', heating: 'Forced Air Gas', cooling: 'Central Air' },
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    }
]
